# Generated by Django 5.1.7 on 2025-05-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_learning_session_alter_answer_attempt_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning_session',
            name='duration',
            field=models.IntegerField(default=-1),
        ),
    ]
