# Generated by Django 5.1.7 on 2025-05-01 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_learning_session_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning_session',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
