# Generated by Django 5.1.7 on 2025-05-05 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_category_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_repetition',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 5, 6, 34, 558811)),
        ),
    ]
