# Generated by Django 5.1.7 on 2025-05-05 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_word_repetition_next_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='word_repetition',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 14, 52, 53, 404995)),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('word', 'translation', 'transcription')},
        ),
    ]
