# Generated by Django 5.1.7 on 2025-05-08 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_word_word_alter_word_repetition_next_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='word_repetition',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 1, 40, 0, 608725, tzinfo=datetime.timezone.utc)),
        ),
    ]
