# Generated by Django 5.1.7 on 2025-05-08 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_repetition',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 21, 0, 24, 716671, tzinfo=datetime.timezone.utc)),
        ),
    ]
