# Generated by Django 5.1.7 on 2025-05-09 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_repetition',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 9, 2, 23, 14, 350655, tzinfo=datetime.timezone.utc)),
        ),
    ]
