# Generated by Django 5.2.1 on 2025-05-09 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_word_repetition_next_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='word_repetition',
            name='ml_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='word_repetition',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 9, 17, 53, 38, 24492, tzinfo=datetime.timezone.utc)),
        ),
    ]
