# Generated by Django 5.2.1 on 2025-05-09 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_word_repetition_ml_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word_repetition',
            name='ml_data',
        ),
        migrations.AlterField(
            model_name='word_repetition',
            name='next_review',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 9, 19, 27, 25, 828210, tzinfo=datetime.timezone.utc)),
        ),
    ]
